### PR TITLE
fix the files in the proprietary-files.txt

### PR DESCRIPTION
**Pull request by mskyaxl**
@hellobbn, impressive how much you managed to progress in this project! Great work!

I found these 2 issues in this file.

The path should always be relative to /system :)

### CODE REVIEW

**Review by hellobbn — COMMENTED** [review]
Thanks for your pull request.

I think it is required to change `system/lib64` to `lib64`. 
However, I am not sure I should change `odm/` to `../odm`...
The rootfs dump that I generated has the following layout:
```
.
├── acct
├── apex
├── config
├── d -> /sys/kernel/debug
├── data
├── data_mirror
├── debug_ramdisk
├── dev
├── linkerconfig
├── lost+found
├── metadata
├── mnt
├── odm
├── odm_dlkm
├── oem
├── postinstall
├── proc
├── product
├── second_stage_resources
├── storage
├── sys
├── system
├── system_ext -> system/system_ext
├── vendor
└── vendor_dlkm
```

And if we use the following command: `extract-files.sh [rootdir-folder]` then the odm resides in the `[rootdir-folder]/` path, not relative to the system folder.

I haven't looked closely at the blob extraction scripts yet, though.

**Comment by mskyaxl** [comment]
in /system there are symlinks to all other directories except for /odm and the blob extraction script is looking into /system/<src>

**Comment by hellobbn** [comment]
Yes I understand that. But I checked proprietary file list in official LineageOS device tree and it seems they do not use `../odm`...
And using `odm` will not cause the extract script to fail.

odm is linked to vendor/odm

https://github.com/search?q=org%3ALineageOS+odm%2F+proprietary&type=Code

**Comment by mskyaxl** [comment]
vendor/odm also works :)

if you keep /odm/<path> I get:

`➜  pdx203 git:(0959f14) ✗ vim proprietary-files.txt
➜  pdx203 git:(0959f14) ✗ ./extract-files.sh
Cleaning output directory (./../../../vendor/sony/pdx203/proprietary)..
Extracting 2359 files in ./proprietary-files.txt from adb:
  - etc/permissions/privapp-permissions-qti.xml
  - etc/sysconfig/qti_whitelist.xml
  - vendor/lib/libMiscTaWrapper.so
  - vendor/lib/vendor.somc.hardware.miscta@1.0.so
  - vendor/lib64/libMiscTaWrapper.so
  - vendor/lib64/vendor.somc.hardware.miscta@1.0.so
  - odm/bin/sony_ext_uim_ctrl
    !! odm/bin/sony_ext_uim_ctrl: file not found in source
  - odm/etc/init/sony_ext_uim_ctrl.rc
    !! odm/etc/init/sony_ext_uim_ctrl.rc: file not found in source
  - product/etc/permissions/telephony_product_privapp-permissions-qti.xml
  - system_ext/bin/dpmd
  - system_ext/bin/wfdservice
`

**Comment by hellobbn** [comment]
OK, lets try this, if you unsin the `super_X-FLASH-ALL-2389.sin` and get `super_X-FLASH-ALL-2389.img`, and then you convert it to android sparse image file type: `img2simg super_X-FLASH-ALL-2389.img super.img` and put the super.img in some rootfs folder (for example, /data/rootfs/super.img), and use the following command:

```
./extract-files.sh /data/rootfs
```

And the script will extract everything from that `super.img` for you, and odm is fine.

So I do not have strong opinion to change `odm/` to `/vendor/odm` or `../odm`, etc.

**Comment by mskyaxl** [comment]
@hellobbn , it does not work with `/vendor/odm` when using the .img as input but it is working when connecting via adb to the phone so most likely that simlink from /vendor is not kept when super.img is extracted.

`../odm` works in both cases

**Comment by hellobbn** [comment]
Can you confirm that the `../odm` produces a build where the `uim_ctrl` exec work?

**Comment by mskyaxl** [comment]
I have updated this branch with other commits. I will recreate a cleaner PR

**Pull request closed without merging**
